// <auto-generated />
using System;
using Borboteca_Libros.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Borboteca_Libros.AccessData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211204030921_libros")]
    partial class libros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Autor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreCompleto = "Antoine de Saint-Exupéry"
                        },
                        new
                        {
                            Id = 2,
                            NombreCompleto = "Javier Alexis Villa"
                        },
                        new
                        {
                            Id = 3,
                            NombreCompleto = "Carlos Javier Suarez"
                        },
                        new
                        {
                            Id = 4,
                            NombreCompleto = "Tomas Rojas"
                        },
                        new
                        {
                            Id = 5,
                            NombreCompleto = "Anonimo"
                        },
                        new
                        {
                            Id = 6,
                            NombreCompleto = "Vicente Blasco Ibañez"
                        });
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Novela"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Terror"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Comedia"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Ficción"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Aventura"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Suspenso"
                        });
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Libro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaDePublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pach")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Resenia")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2550e1b1-9e48-43b4-875f-14634d4c07f1"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://www.elsotano.com/imagenes/9788431/978843155164.JPG",
                            Pach = "C:/Borboteca-libros/frutas_del_mundo.pdf",
                            Precio = 3000,
                            Resenia = "La fruta ocupa un lugar fundamental en la dita mediterránea, y todos conocemos las enormes ventajas de integrarla en la alimentación. Nos resulta muy habitual su consumo, y en nuestro país es muy común ver campos cultivados con las más diversas especies. Además, gracias a la globalización del mercado y la rapidez en los transportes, podemos acceder a numerosas frutas que hace un tiempo nos eran desconocidas. Susanna Lyle ha elaborado esta guía exhaustiva que pretende ser una fuente de inspiración para todo aquel que desee cultivar y probar nuevos alimentos. Incluye especies muy comunes y otras menos conocidas, pero igualmente interesantes, que crecen en climas templados y subtropicales. Se presentan más de 300, y se proporciona información detallada sobre cada una, lo que hace de esta obra un enciclopedia única.",
                            Titulo = "Frutas del mundo"
                        },
                        new
                        {
                            Id = new Guid("a76d59d2-3cb0-44b3-9041-4421e14c69c3"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://viajes.nationalgeographic.com.es/medio/2021/08/23/la-exclusiva-costa-de-na-pali_a5d66976_2000x1333.jpg",
                            Pach = "C:/Borboteca-libros/hawai.pdf",
                            Precio = 2000,
                            Resenia = "'Hawai' es la historia de hombres y mujeres de distintas razas, religiones, costumbres y tradiciones, que cruzaron los mares atraídos por el hechizo de esas islas. James Michener concentra el interés del lector en un grupo familiar que vive las emociones, idilios y aventuras propias del ambiente que imperaba en las islas. Todo el acento de esta novela ha sido puesto por el autor en los personajes y en sus triunfos, tragedias, amores y odios personales.",
                            Titulo = "Hawai"
                        },
                        new
                        {
                            Id = new Guid("72b51e64-c5e0-40cc-9022-9f0d3906dcc3"),
                            AutorId = 1,
                            Editorial = "Desconocida",
                            FechaDePublicacion = new DateTime(2021, 10, 23, 14, 4, 18, 787, DateTimeKind.Unspecified),
                            Imagen = "https://static.ellitoral.com/um/fotos/294484_princi.jpg",
                            Pach = "C:/Borboteca-libros/El_Principito_completo.pdf",
                            Precio = 5000,
                            Resenia = "El principito es una novela corta y la obra más famosa del escritor y aviador francés Antoine de Saint-Exupéry.",
                            Titulo = "El principito"
                        },
                        new
                        {
                            Id = new Guid("2650baa6-334b-4e17-b7d5-9f773f964e37"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://pics.filmaffinity.com/the_great_global_warming_swindle_tv_tv-508851081-large.jpg",
                            Pach = "C:/Borboteca-libros/el_gran_fraude_del_calentamiento_global.pdf",
                            Precio = 1000,
                            Resenia = "Free Spotlight trancribe este análisis realizado por expertos sobre la teoria del “calentamiento global por culpa del ser humano”, un tema tan polémico como inserto en la sociedad actual.",
                            Titulo = "El gran fraude del calentamiento global"
                        },
                        new
                        {
                            Id = new Guid("b8778f7a-15ba-40a0-a66c-a50a7b01f2f3"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://www.tuslibros.com/2d_covers/upscaled/1332021893.jpg",
                            Pach = "C:/Borboteca-libros/la_correccion.pdf",
                            Precio = 1500,
                            Resenia = "Tras el suicidio de su amigo Roithamer, el anónimo narrador de la novela llega a la casa del taxidermista Höller, en cuya buhardilla el suicida ha permanecido durante seis años entregado a la tarea de planear y construir, en el centro geométrico exacto del bosque de Kobernauss, un Cono que, desafiando las leyes de la construcción tradicional, estaba destinado a ser residencia y «felicidad suprema» de su hermana. Urdida en torno a un proceso obsesivo de creación y destrucción que se plasma en un afán de constante corrección, la novela es una reflexión sobre los problemas del hombre contemporáneo, enfrentado a la deshumanización, el desamor y la soledad.",
                            Titulo = "La correccion"
                        },
                        new
                        {
                            Id = new Guid("2dd83fca-7e9f-45d0-a7df-a9e734bf1e79"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://www.minceraft.cl/media/k2/items/cache/4d914480da9f0e177f0711403821d47b_M.jpg",
                            Pach = "C:/Borboteca-libros/lo_que_es_bueno_para_ti_es_malo_para_mí.pdf",
                            Precio = 4000,
                            Resenia = "Se trata de una persona que entendió la vida",
                            Titulo = "Lo que es bueno para ti es malo para mi"
                        },
                        new
                        {
                            Id = new Guid("67f3d74e-039e-415c-8f82-be1a87111b3f"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://m.media-amazon.com/images/I/413zycyOWKL.jpg",
                            Pach = "C:/Borboteca-libros/la_barraca.pdf",
                            Precio = 3000,
                            Resenia = "El tema de La Barraca es la injusticia de las personas ignorantes y pobres, cuyo sentido de la existencia se basa en la supervivencia. En esta novela critica a la vez que describe la sociedad de la época. Dicha novela cuenta la desgraciada historia de una familia pobre en la huerta valenciana.",
                            Titulo = "La barraca"
                        },
                        new
                        {
                            Id = new Guid("3fe0deba-7374-4293-9067-c0ede9c768fe"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://estaticos.muyinteresante.es/media/cache/1140x_thumb/uploads/images/gallery/5e5fce075bafe8711d08b2d5/nombres-luna_1.jpg",
                            Pach = "C:/Borboteca-libros/lo_que_la_luna_grande_cambio.pdf",
                            Precio = 2000,
                            Resenia = "Libro de inspiración que nos cuenta los grandes cambios de un satélite natural de la tierra",
                            Titulo = "Lo que la luna grande cambio"
                        },
                        new
                        {
                            Id = new Guid("1759cd7f-a67e-419e-8923-db27b73b637d"),
                            AutorId = 5,
                            Editorial = "Freak World",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://www.storytel.com/images/e/200x200/0002398771.jpg",
                            Pach = "C:/Borboteca-libros/a_los_pies_de_venus.pdf",
                            Precio = 3000,
                            Resenia = "Continuación de El Papa del Mar, en la que se da inicio a la historia amorosa que liga a Claudio Borja, un joven poeta valenciano, y Rosaura Salcedo, una rica dama argentina, esta novela en la que prosiguen sus avatares puede leerse perfectamente, sin embargo, como novela suelta.",
                            Titulo = "A los pies de Venus"
                        },
                        new
                        {
                            Id = new Guid("93cd1293-5d5e-455e-a2cc-deaa1eceb064"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Nyolcvan_nap_alatt_a_F%C3%B6ld_k%C3%B6r%C3%BCl.jpg/220px-Nyolcvan_nap_alatt_a_F%C3%B6ld_k%C3%B6r%C3%BCl.jpg",
                            Pach = "C:/Borboteca-libros/la_vuelta_al_mundo_de_un_novelista_tomo_i.pdf",
                            Precio = 3000,
                            Resenia = "Es un carrusel ameno e inolvidable de lugares, pueblos y personas en el que Blasco, como incomparable compañero de viaje, hace desfilar ante nuestros ojos la espléndida y fascinante variedad de unos paisajes de leyenda hoy en gran parte trivializados o desaparecidos",
                            Titulo = "La vuelta al mundo de un novelista"
                        },
                        new
                        {
                            Id = new Guid("e87266d6-99cb-4afd-849b-89c49d36c250"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://www.tuslibros.com/2d_covers/large/1509826828.jpg",
                            Pach = "C:/Borboteca-libros/idioteces_de_los_idiotas_y_otras_tonterías.pdf",
                            Precio = 6000,
                            Resenia = "Es el escritor actual en español más leído del mundo, y leyendo sus relatos se comprende el por qué: sencillamente porque nos divierte con sus brillantes reflexiones sobre temas cotidianos que a todos nos afectan. ",
                            Titulo = "Idioteces de los idiotas y otras tonterías"
                        },
                        new
                        {
                            Id = new Guid("ebf123b7-0841-40ea-9546-ff7ccc17835c"),
                            AutorId = 5,
                            Editorial = "Free Editorial",
                            FechaDePublicacion = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://http2.mlstatic.com/D_NQ_NP_2X_822295-MLA45613745505_042021-F.webp",
                            Pach = "C:/Borboteca-libros/en_la_puerta_del_cielo.pdf",
                            Precio = 3000,
                            Resenia = "Antes de desaparecer junto a su ayudante americana, el astrofísico Lalo Múgica informa a una de sus vecinas de que ha encontrado las claves para abrir la puerta del cielo. Gerardo Vilela, un sencillo profesor de Instituto, gana una beca que le lleva de Lugo a Madrid. Cuando las enigmáticas vecinas del número 12 le realquilan la antigua casa de Múgica, él se siente feliz. Pero el ático guarda algo para él: un acta firmada por Pilatos que narra otra desaparición ocurrida en Judea el año de la muerte de Jesucristo. Con veinte siglos de diferencia, ambas desapariciones parecen estar extrañamente relacionadas..",
                            Titulo = "En la puerta del cielo"
                        });
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.LibroGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<Guid>("LibroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("LibroId");

                    b.ToTable("LibroGenero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneroId = 5,
                            LibroId = new Guid("2550e1b1-9e48-43b4-875f-14634d4c07f1")
                        },
                        new
                        {
                            Id = 2,
                            GeneroId = 5,
                            LibroId = new Guid("a76d59d2-3cb0-44b3-9041-4421e14c69c3")
                        },
                        new
                        {
                            Id = 3,
                            GeneroId = 3,
                            LibroId = new Guid("e87266d6-99cb-4afd-849b-89c49d36c250")
                        },
                        new
                        {
                            Id = 4,
                            GeneroId = 5,
                            LibroId = new Guid("e87266d6-99cb-4afd-849b-89c49d36c250")
                        },
                        new
                        {
                            Id = 5,
                            GeneroId = 4,
                            LibroId = new Guid("2650baa6-334b-4e17-b7d5-9f773f964e37")
                        },
                        new
                        {
                            Id = 6,
                            GeneroId = 1,
                            LibroId = new Guid("b8778f7a-15ba-40a0-a66c-a50a7b01f2f3")
                        },
                        new
                        {
                            Id = 7,
                            GeneroId = 1,
                            LibroId = new Guid("2dd83fca-7e9f-45d0-a7df-a9e734bf1e79")
                        },
                        new
                        {
                            Id = 8,
                            GeneroId = 4,
                            LibroId = new Guid("67f3d74e-039e-415c-8f82-be1a87111b3f")
                        },
                        new
                        {
                            Id = 9,
                            GeneroId = 6,
                            LibroId = new Guid("3fe0deba-7374-4293-9067-c0ede9c768fe")
                        },
                        new
                        {
                            Id = 10,
                            GeneroId = 4,
                            LibroId = new Guid("93cd1293-5d5e-455e-a2cc-deaa1eceb064")
                        },
                        new
                        {
                            Id = 11,
                            GeneroId = 1,
                            LibroId = new Guid("ebf123b7-0841-40ea-9546-ff7ccc17835c")
                        },
                        new
                        {
                            Id = 12,
                            GeneroId = 4,
                            LibroId = new Guid("2550e1b1-9e48-43b4-875f-14634d4c07f1")
                        },
                        new
                        {
                            Id = 13,
                            GeneroId = 1,
                            LibroId = new Guid("a76d59d2-3cb0-44b3-9041-4421e14c69c3")
                        },
                        new
                        {
                            Id = 14,
                            GeneroId = 4,
                            LibroId = new Guid("b8778f7a-15ba-40a0-a66c-a50a7b01f2f3")
                        });
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Libro", b =>
                {
                    b.HasOne("Borboteca_Libros.Domain.Entities.Autor", "Autor")
                        .WithMany("Libro")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.LibroGenero", b =>
                {
                    b.HasOne("Borboteca_Libros.Domain.Entities.Genero", "Genero")
                        .WithMany("LibroGenero")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Borboteca_Libros.Domain.Entities.Libro", "Libro")
                        .WithMany("LibroGenero")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Autor", b =>
                {
                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Genero", b =>
                {
                    b.Navigation("LibroGenero");
                });

            modelBuilder.Entity("Borboteca_Libros.Domain.Entities.Libro", b =>
                {
                    b.Navigation("LibroGenero");
                });
#pragma warning restore 612, 618
        }
    }
}
